export { default as Top } from "component/main_content/Top";
export { default as Rule } from "component/main_content/Rule";
export { default as Stage1 } from "component/main_content/Stage1";
export { default as Stage2 } from "component/main_content/Stage2";
export { default as Stage3 } from "component/main_content/Stage3";
export { default as Stage4 } from "component/main_content/Stage4";
export { default as Stage5 } from "component/main_content/Stage5";
export { default as GameOver } from "component/main_content/GameOver";
export { default as Clear } from "component/main_content/Clear";
